### ISSUE TITLE
JSON output is enclosed in double array

### ISSUE THREAD

**Issue by fabriziobertocci** [GaloisInc/daedalus#104]
When using daedalus with `--json` argument, the older version would produce something like this:
```
--- Found 1 results:
[ { "bb": 182
  , "i8_1": 33
  , "ul_1": 29320907
 }, { ... } 
]
```
But the new version produces:
```
[ [ { "bb": 182
  , "i8_1": 33
  , "ul_1": 29320907
 }, { ... } 
] ]
```
(older version for me is the build I did back at the beginning of March, I don't have the exact has of the version)

I'm happy that the first line (`--- Found 1 results:`) is now gone, but why the double array?

**Comment by yav** [comment]
So technically this is a feature not a bug, although I can see it being annoying :)    In general, `deadalus` can deal with ambiguous grammars, so if a grammar is ambiguous you would get a list of possible results (e.g., try writing `def Main = Match 'a' | Match 'a'`).  If it is not, which is usually the case, you get just a singleton list.   Since your grammar probably produces a list, and is not ambiguous you are getting the double list, which is kind of the equivalent of saying "found 1 result".

Dealing with ambiguous grammars is pretty complicated, so it would be nicer for both the code generator an the daedalus user if we could spot that a grammar is ambiguous statically, without having to run the parser.  Unfortunately, this is non-trivial for the very rich set of grammars supported by `daedalus` at the moment.  We are, however, working on an analysis that would, hopefully, work well for most common grammars, and once that's functional, we should be able to say ahead of time if the grammar is unambigous, or "possibly ambiguous".

In the shorter term, we could also do something like: only show the first result, and maybe print a warning if there was more than one result, if that would be more helpful?

**Comment by fabriziobertocci** [comment]
Iavor: I understand. No need to change anything. I just needed to understand why there were nested arrays. For me it's just a matter of dealing with it (when using the output, if I detect two top-level elements I can warn of ambiguous grammar, otherwise take the first and only result).

Thanks for explaining. This is good.
Fab
