### ISSUE TITLE
text-extraction bug

### ISSUE THREAD

**Issue by mtullsen** [GaloisInc/daedalus#191]
We have a very simple "Hello World" pdf but text-extraction only extracts the "Hello":
```
daedalus $ pdf-hs-driver --faw --text pdf-driver/pdf_tests/handcrafted_minimal/1_valid_xref_strm.pdf

INFO: File size 967 bytes.
INFO:662 Found pointer to xref table/stream.
INFO: 11 xref entries.
INFO: Root reference is R:3:0
INFO: Catalog value:
"\nHELLO"
...
```

**Comment by wrharris** [comment]
When a String contains whitespace, the parser succeeds but only returns the substring up to the first whitespace.

Hunch is that the bug is in `ExtractStringType1`, which translates uint8 to unicode by parsing the string: if it failed on a whitespace, it would still return everything up to the whitespace.

**Comment by wrharris** [comment]
The StandardEncoding dictionary of character codes to glyphs is missing several entries, including one for space. Likely due to bug in extracting the encoding table, which annotates a small set of glyphs with a superscript.

**Comment by wrharris** [comment]
This was indeed the issue: helloworld.pdf now works.
